Update kernel_test.yml

diff --git a/.github/workflows/kernel_test.yml b/.github/workflows/kernel_test.yml
--- a/.github/workflows/kernel_test.yml
+++ b/.github/workflows/kernel_test.yml
@@ -405,9 +405,11 @@ jobs:
           make ${{ env.ARGS }} ${{ env.KERNEL_DEFCONFIG_PATH }}
 
       - name: ⚙️ Apply Kernel Config Changes
+        working-directory: ${{ env.KERNEL_NAME }}
         env:
           JSON_CONFIG: '${{ toJSON(matrix.CONFIG) }}'
-          run: |
+          ARGS: ${{ steps.generate-args.outputs.ARGS }}
+        run: |
             if [ -z "$(echo "$JSON_CONFIG" | jq '.KernelConfigChanges | select(length > 0)')" ]; then
               echo "🤔 No kernel config changes found. Skipping..."
               exit 0
@@ -418,35 +420,34 @@ jobs:
 
             cd ${{ env.OUT_DIR }}
             for encoded_change in $CONFIG_CHANGES; do
-            decoded_change=$(echo "$encoded_change" | base64 --decode)
+              decoded_change=$(echo "$encoded_change" | base64 --decode)
 
-            action=$(echo "$decoded_change" | jq -r '.action')
-            config=$(echo "$decoded_change" | jq -r '.config')
-            value=$(echo "$decoded_change" | jq -r '.value')
+              action=$(echo "$decoded_change" | jq -r '.action')
+              config=$(echo "$decoded_change" | jq -r '.config')
+              value=$(echo "$decoded_change" | jq -r '.value')
 
-            echo "🤔 Action: $action, Config: $config, Value: $value"
-            case "$action" in
-              "enable" | "disable" | "module")
-                ./../scripts/config --file .config --"$action" "$config"
-                ;;
-              "set-val" | "set-str")
-                if [ "$value" == "null" ]; then
-                  echo "Error: 'value' is missing for action '$action' on config '$config'"
+              echo "=> Action: $action, Config: $config, Value: $value"
+              case "$action" in
+                "enable" | "disable" | "module")
+                  ./../scripts/config --file .config --"$action" "$config"
+                  ;;
+                "set-val" | "set-str")
+                  if [ "$value" == "null" ]; then
+                    echo "Error: 'value' is missing for action '$action' on config '$config'"
+                    exit 1
+                  fi
+                  ./../scripts/config --file .config --"$action" "$config" "$value"
+                  ;;
+                *)
+                  echo "Error: Unknown action '$action' for config '$config'"
                   exit 1
-                fi
-                ./../scripts/config --file .config --"$action" "$config" "$value"
-                ;;
-              *)
-                echo "Error: Unknown action '$action' for config '$config'"
-                exit 1
-                ;;
+                  ;;
               esac
             done
 
             echo "🤔 All kernel config changes applied successfully."
             echo "🤔 Finalizing config with 'olddefconfig'..."
-            make ${{ steps.generate-args.outputs.ARGS }} olddefconfig
-            cd ${{ env.WORKSPACE }}
+            make ${{ env.ARGS }} olddefconfig
 
       - name: 😭 Continue building the kernel
         working-directory: ${{ env.KERNEL_NAME }}
